version: '3.8'

services:
  database:
    container_name: lumi-container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lumi
      - POSTGRES_PASSWORD=lumi
      - POSTGRES_DB=mydb
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
